/*
 * Copyright (c) 2019 SUSE LLC
 *
 * Licensed under LGPL-2.1 (see LICENSE)
 */

#include "common.h"
#include "scsi_trace.h"

#define CASE_STR(x) case x: return #x;

// TODO: unused, remove this.
PCHAR SRB_STATUS_STRINGS[] = {
    (PCHAR)"SRB_STATUS_PENDING                  0x00",
    (PCHAR)"SRB_STATUS_SUCCESS                  0x01",
    (PCHAR)"SRB_STATUS_ABORTED                  0x02",
    (PCHAR)"SRB_STATUS_ABORT_FAILED             0x03",
    (PCHAR)"SRB_STATUS_ERROR                    0x04",
    (PCHAR)"SRB_STATUS_BUSY                     0x05",
    (PCHAR)"SRB_STATUS_INVALID_REQUEST          0x06",
    (PCHAR)"SRB_STATUS_INVALID_PATH_ID          0x07",
    (PCHAR)"SRB_STATUS_NO_DEVICE                0x08",
    (PCHAR)"SRB_STATUS_TIMEOUT                  0x09",
    (PCHAR)"SRB_STATUS_SELECTION_TIMEOUT        0x0A",
    (PCHAR)"SRB_STATUS_COMMAND_TIMEOUT          0x0B",
    (PCHAR)"SRB_STATUS_MESSAGE_REJECTED         0x0D",
    (PCHAR)"SRB_STATUS_BUS_RESET                0x0E",
    (PCHAR)"SRB_STATUS_PARITY_ERROR             0x0F",
    (PCHAR)"SRB_STATUS_REQUEST_SENSE_FAILED     0x10",
    (PCHAR)"SRB_STATUS_NO_HBA                   0x11",
    (PCHAR)"SRB_STATUS_DATA_OVERRUN             0x12",
    (PCHAR)"SRB_STATUS_UNEXPECTED_BUS_FREE      0x13",
    (PCHAR)"SRB_STATUS_PHASE_SEQUENCE_FAILURE   0x14",
    (PCHAR)"SRB_STATUS_BAD_SRB_BLOCK_LENGTH     0x15",
    (PCHAR)"SRB_STATUS_REQUEST_FLUSHED          0x16",
    (PCHAR)"SRB_STATUS_INVALID_LUN              0x20",
    (PCHAR)"SRB_STATUS_INVALID_TARGET_ID        0x21",
    (PCHAR)"SRB_STATUS_BAD_FUNCTION             0x22",
    (PCHAR)"SRB_STATUS_ERROR_RECOVERY           0x23",
    (PCHAR)"SRB_STATUS_NOT_POWERED              0x24",
    (PCHAR)"SRB_STATUS_LINK_DOWN                0x25"
};

_Use_decl_annotations_
PCHAR
WnbdToStringSrbFunction(UCHAR SrbFunction)
{
    switch(SrbFunction) {
    CASE_STR(SRB_FUNCTION_EXECUTE_SCSI)
    CASE_STR(SRB_FUNCTION_CLAIM_DEVICE)
    CASE_STR(SRB_FUNCTION_IO_CONTROL)
    CASE_STR(SRB_FUNCTION_RECEIVE_EVENT)
    CASE_STR(SRB_FUNCTION_RELEASE_QUEUE)
    CASE_STR(SRB_FUNCTION_ATTACH_DEVICE)
    CASE_STR(SRB_FUNCTION_RELEASE_DEVICE)
    CASE_STR(SRB_FUNCTION_SHUTDOWN)
    CASE_STR(SRB_FUNCTION_FLUSH)
    CASE_STR(SRB_FUNCTION_PROTOCOL_COMMAND)
    CASE_STR(SRB_FUNCTION_ABORT_COMMAND)
    CASE_STR(SRB_FUNCTION_RELEASE_RECOVERY)
    CASE_STR(SRB_FUNCTION_RESET_BUS)
    CASE_STR(SRB_FUNCTION_RESET_DEVICE)
    CASE_STR(SRB_FUNCTION_TERMINATE_IO)
    CASE_STR(SRB_FUNCTION_FLUSH_QUEUE)
    CASE_STR(SRB_FUNCTION_REMOVE_DEVICE)
    CASE_STR(SRB_FUNCTION_WMI)
    CASE_STR(SRB_FUNCTION_LOCK_QUEUE)
    CASE_STR(SRB_FUNCTION_UNLOCK_QUEUE)
    CASE_STR(SRB_FUNCTION_QUIESCE_DEVICE)
    CASE_STR(SRB_FUNCTION_RESET_LOGICAL_UNIT)
    CASE_STR(SRB_FUNCTION_SET_LINK_TIMEOUT)
    CASE_STR(SRB_FUNCTION_LINK_TIMEOUT_OCCURRED)
    CASE_STR(SRB_FUNCTION_LINK_TIMEOUT_COMPLETE)
    CASE_STR(SRB_FUNCTION_POWER)
    CASE_STR(SRB_FUNCTION_PNP)
    CASE_STR(SRB_FUNCTION_DUMP_POINTERS)
    CASE_STR(SRB_FUNCTION_FREE_DUMP_POINTERS)
    default:
        return "UNKNOWN_SRB_FUNCTION";
    }
}

_Use_decl_annotations_
PCHAR
WnbdToStringSrbStatus(UCHAR SrbStatus)
{
    switch(SrbStatus) {
    CASE_STR(SRB_STATUS_PENDING)
    CASE_STR(SRB_STATUS_SUCCESS)
    CASE_STR(SRB_STATUS_ABORTED)
    CASE_STR(SRB_STATUS_ABORT_FAILED)
    CASE_STR(SRB_STATUS_ERROR)
    CASE_STR(SRB_STATUS_BUSY)
    CASE_STR(SRB_STATUS_INVALID_REQUEST)
    CASE_STR(SRB_STATUS_INVALID_PATH_ID)
    CASE_STR(SRB_STATUS_NO_DEVICE)
    CASE_STR(SRB_STATUS_TIMEOUT)
    CASE_STR(SRB_STATUS_SELECTION_TIMEOUT)
    CASE_STR(SRB_STATUS_COMMAND_TIMEOUT)
    CASE_STR(SRB_STATUS_MESSAGE_REJECTED)
    CASE_STR(SRB_STATUS_BUS_RESET)
    CASE_STR(SRB_STATUS_PARITY_ERROR)
    CASE_STR(SRB_STATUS_REQUEST_SENSE_FAILED)
    CASE_STR(SRB_STATUS_NO_HBA)
    CASE_STR(SRB_STATUS_DATA_OVERRUN)
    CASE_STR(SRB_STATUS_UNEXPECTED_BUS_FREE)
    CASE_STR(SRB_STATUS_PHASE_SEQUENCE_FAILURE)
    CASE_STR(SRB_STATUS_BAD_SRB_BLOCK_LENGTH)
    CASE_STR(SRB_STATUS_REQUEST_FLUSHED)
    CASE_STR(SRB_STATUS_INVALID_LUN)
    CASE_STR(SRB_STATUS_INVALID_TARGET_ID)
    CASE_STR(SRB_STATUS_BAD_FUNCTION)
    CASE_STR(SRB_STATUS_ERROR_RECOVERY)
    CASE_STR(SRB_STATUS_NOT_POWERED)
    CASE_STR(SRB_STATUS_LINK_DOWN)
// Recent SDK additions
#ifdef SRB_STATUS_INSUFFICIENT_RESOURCES
    CASE_STR(SRB_STATUS_INSUFFICIENT_RESOURCES)
#endif
#ifdef SRB_STATUS_THROTTLED_REQUEST
    CASE_STR(SRB_STATUS_THROTTLED_REQUEST)
#endif
    default:
        return "UNKNOWN_SRB_STATUS";
    }
}
